db:
  image: postgres:9.4

server:
  build: ./server
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - 8000:8000
  links:
    - db
  environment:
    DATABASE_URL: postgres://postgres@db/postgres

client:
  build: ./client
  ports:
    - 3000:3000
    - 8080:8080
  links:
    - server
  environment:
    PORT: 3000
